name: Build Check

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  build:
    name: Build project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Clean repository
        run: make fclean
      - name: Build project
        run: make