name: Reports

on:
  workflow_run:
    workflows: [unit_tests]
    types: [completed]

permissions:
  checks: write

jobs:
  tests_report:
    name: Unit tests report
    runs-on: ubuntu-latest
    steps:
      - name: Download Test Report
        uses: dawidd6/action-download-artifact@v2
        with:
          name: tests_results
          workflow: ${{ github.event.workflow.id }}
          run_id: ${{ github.event.workflow_run.id }}
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: always()
        with:
          report_paths: tests_results.xml
          commit: ${{github.event.workflow_run.head_sha}}
          require_tests: false
          require_passed_tests: true
          include_passed: true
          detailed_summary: true
          job_name: Unit tests report
  
  coverage_report:        
    name: Unit tests report
    runs-on: ubuntu-latest
    steps:
      - name: Download coverage Report
        uses: dawidd6/action-download-artifact@v2
        with:
          name: tests_coverage
          workflow: ${{ github.event.workflow.id }}
          run_id: ${{ github.event.workflow_run.id }}

      - name: Code Coverage Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: coverage.xml
          badge: true
          fail_below_min: false
          format: markdown
          hide_branch_rate: false
          hide_complexity: false
          indicators: true
          output: both
          thresholds: '60 80'
      - name: Coverage summary
        run: cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY